### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Veritogen** [kevinlekiller/Hyperion_Grabber_X11_QT#1]
Hello! 
I get a error when trying to compile on Ubuntu 18.04. I cloned from git and could run `cmake .` but not `make`. When (re)trying, I get the following error. 
`Building CXX object CMakeFiles/Hyperion_Grabber_X11_QT.dir/hgx11grab.cpp.o
/home/user/Hyperion_Grabber_X11_QT/hgx11grab.cpp: In member function ‘void hgx11grab::grabFrame()’:
/home/user/Hyperion_Grabber_X11_QT/hgx11grab.cpp:174:91: error: ‘class QImage’ has no member named ‘sizeInBytes’
     imgdata_m = QByteArray::fromRawData(reinterpret_cast<const char *>(qimg.bits()), qimg.sizeInBytes()).toBase64().data();
                                                                                           ^~~~~~~~~~~
CMakeFiles/Hyperion_Grabber_X11_QT.dir/build.make:158: recipe for target 'CMakeFiles/Hyperion_Grabber_X11_QT.dir/hgx11grab.cpp.o' failed
make[2]: *** [CMakeFiles/Hyperion_Grabber_X11_QT.dir/hgx11grab.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Hyperion_Grabber_X11_QT.dir/all' failed
make[1]: *** [CMakeFiles/Hyperion_Grabber_X11_QT.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`
To me it seems like a bug in the code. From what I understand the error is based on the change from ` imgdata_m = QByteArray::fromRawData(reinterpret_cast<const char *>(qimg.bits()), qimg.byteCount()).toBase64().data(); ` to `imgdata_m = QByteArray::fromRawData(reinterpret_cast<const char *>(qimg.bits()), qimg.sizeInBytes()).toBase64().data(); ` on line 174 in  hgx11grab.cpp. Compiling worked when I changed the line to the version before the latest commit.

**Comment by kevinlekiller** [comment]
I think the issue is Ubuntu 18.04's QT is too old, sizeInBytes was added in 5.10, you can maybe use QImage::byteCount() instead (edit: I see you did - I changed to sizeInBytes because byteCount is deprecated now).

https://doc.qt.io/qt-5/qimage.html#sizeInBytes
